services:
  - type: static
    name: virtual-medical-frontend
    env: static
    branch: main
    buildCommand: npm install && npm run build
    publishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html